version: "3.1"

services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: